### ISSUE TITLE
Not asking for file permissions

### ISSUE THREAD

**Issue by se-bastiaan** [Plunderbund/Plunder#1]
I just noticed you forked a fork of my TorrentStream library and was really interested in what you were using it for. And I must say I was really impressed.

So I wrote a basic provider just to see how well this works and found the app does not ask for file permissions on Marshmallow yet. I understand that the app may not be finished yet, but I just wanted to let you know.

**Comment by Plunderbund** [comment]
Thanks for the report Sébastiaan, this had been fixed with 97a9d7d608f2c0da16a13e5cf2e702012b07a652 but not pushed, my mistake!

Great work on TorrentStream, it's much appreciated. It's still early days yet (TODO: readme...) but I'm excited for what I have planned. I didn't expect anybody to find this repository quite yet so your feedback is greatly appreciated!
